"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.26.46
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.controller_settings_oidc import ControllerSettingsOidc
globals()['ControllerSettingsOidc'] = ControllerSettingsOidc
from openziti_edge_management.model.controller_settings import ControllerSettings


class TestControllerSettings(unittest.TestCase):
    """ControllerSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testControllerSettings(self):
        """Test ControllerSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ControllerSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
