"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.26.46
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.controller_setting_patch_all_of import ControllerSettingPatchAllOf
from openziti_edge_management.model.controller_settings import ControllerSettings
from openziti_edge_management.model.controller_settings_oidc import ControllerSettingsOidc
from openziti_edge_management.model.tags import Tags
globals()['ControllerSettingPatchAllOf'] = ControllerSettingPatchAllOf
globals()['ControllerSettings'] = ControllerSettings
globals()['ControllerSettingsOidc'] = ControllerSettingsOidc
globals()['Tags'] = Tags
from openziti_edge_management.model.controller_setting_update import ControllerSettingUpdate


class TestControllerSettingUpdate(unittest.TestCase):
    """ControllerSettingUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testControllerSettingUpdate(self):
        """Test ControllerSettingUpdate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ControllerSettingUpdate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
