"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.26.46
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.controller_setting_create_all_of import ControllerSettingCreateAllOf
from openziti_edge_management.model.controller_settings import ControllerSettings
from openziti_edge_management.model.controller_settings_oidc import ControllerSettingsOidc
from openziti_edge_management.model.tags import Tags
globals()['ControllerSettingCreateAllOf'] = ControllerSettingCreateAllOf
globals()['ControllerSettings'] = ControllerSettings
globals()['ControllerSettingsOidc'] = ControllerSettingsOidc
globals()['Tags'] = Tags
from openziti_edge_management.model.controller_setting_create import ControllerSettingCreate


class TestControllerSettingCreate(unittest.TestCase):
    """ControllerSettingCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testControllerSettingCreate(self):
        """Test ControllerSettingCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ControllerSettingCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
