"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.26.46
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.controller_setting_effective import ControllerSettingEffective
from openziti_edge_management.model.meta import Meta
globals()['ControllerSettingEffective'] = ControllerSettingEffective
globals()['Meta'] = Meta
from openziti_edge_management.model.detail_controller_setting_effective_envelope import DetailControllerSettingEffectiveEnvelope


class TestDetailControllerSettingEffectiveEnvelope(unittest.TestCase):
    """DetailControllerSettingEffectiveEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDetailControllerSettingEffectiveEnvelope(self):
        """Test DetailControllerSettingEffectiveEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DetailControllerSettingEffectiveEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
