"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.26.46
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.target_token import TargetToken


class TestTargetToken(unittest.TestCase):
    """TargetToken unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTargetToken(self):
        """Test TargetToken"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TargetToken()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
