"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.26.46
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.api_address_array import ApiAddressArray
globals()['ApiAddressArray'] = ApiAddressArray
from openziti_edge_management.model.api_address_list import ApiAddressList


class TestApiAddressList(unittest.TestCase):
    """ApiAddressList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiAddressList(self):
        """Test ApiAddressList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiAddressList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
