"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.26.46
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.interface import Interface


class TestInterface(unittest.TestCase):
    """Interface unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInterface(self):
        """Test Interface"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Interface()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
