# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.31
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, constr
from openziti_edge_management.models.tags import Tags

class AuthenticatorUpdateWithCurrent(BaseModel):
    """
    All of the fields on an authenticator that will be updated
    """
    password: constr(strict=True, max_length=100, min_length=5) = Field(...)
    tags: Optional[Tags] = None
    username: constr(strict=True, max_length=100, min_length=4) = Field(...)
    current_password: constr(strict=True, max_length=100, min_length=5) = Field(..., alias="currentPassword")
    __properties = ["password", "tags", "username", "currentPassword"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> AuthenticatorUpdateWithCurrent:
        """Create an instance of AuthenticatorUpdateWithCurrent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of tags
        if self.tags:
            _dict['tags'] = self.tags.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> AuthenticatorUpdateWithCurrent:
        """Create an instance of AuthenticatorUpdateWithCurrent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return AuthenticatorUpdateWithCurrent.parse_obj(obj)

        _obj = AuthenticatorUpdateWithCurrent.parse_obj({
            "password": obj.get("password"),
            "tags": Tags.from_dict(obj.get("tags")) if obj.get("tags") is not None else None,
            "username": obj.get("username"),
            "current_password": obj.get("currentPassword")
        })
        return _obj

