# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.31
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr

class AuthPolicySecondary(BaseModel):
    """
    AuthPolicySecondary
    """
    require_ext_jwt_signer: Optional[StrictStr] = Field(None, alias="requireExtJwtSigner")
    require_totp: StrictBool = Field(..., alias="requireTotp")
    __properties = ["requireExtJwtSigner", "requireTotp"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> AuthPolicySecondary:
        """Create an instance of AuthPolicySecondary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if require_ext_jwt_signer (nullable) is None
        # and __fields_set__ contains the field
        if self.require_ext_jwt_signer is None and "require_ext_jwt_signer" in self.__fields_set__:
            _dict['requireExtJwtSigner'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> AuthPolicySecondary:
        """Create an instance of AuthPolicySecondary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return AuthPolicySecondary.parse_obj(obj)

        _obj = AuthPolicySecondary.parse_obj({
            "require_ext_jwt_signer": obj.get("requireExtJwtSigner"),
            "require_totp": obj.get("requireTotp")
        })
        return _obj

