# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.25.31
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class DialBind(str, Enum):
    """
    DialBind
    """

    """
    allowed enum values
    """
    DIAL = 'Dial'
    BIND = 'Bind'

    @classmethod
    def from_json(cls, json_str: str) -> DialBind:
        """Create an instance of DialBind from a JSON string"""
        return DialBind(json.loads(json_str))


