# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.25.31
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field, StrictStr
from openziti_edge_management.models.entity_ref import EntityRef

class IdentityEnrollmentsOttca(BaseModel):
    """
    IdentityEnrollmentsOttca
    """
    ca: Optional[EntityRef] = None
    ca_id: Optional[StrictStr] = Field(None, alias="caId")
    expires_at: Optional[datetime] = Field(None, alias="expiresAt")
    id: Optional[StrictStr] = None
    jwt: Optional[StrictStr] = None
    token: Optional[StrictStr] = None
    __properties = ["ca", "caId", "expiresAt", "id", "jwt", "token"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> IdentityEnrollmentsOttca:
        """Create an instance of IdentityEnrollmentsOttca from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of ca
        if self.ca:
            _dict['ca'] = self.ca.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> IdentityEnrollmentsOttca:
        """Create an instance of IdentityEnrollmentsOttca from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return IdentityEnrollmentsOttca.parse_obj(obj)

        _obj = IdentityEnrollmentsOttca.parse_obj({
            "ca": EntityRef.from_dict(obj.get("ca")) if obj.get("ca") is not None else None,
            "ca_id": obj.get("caId"),
            "expires_at": obj.get("expiresAt"),
            "id": obj.get("id"),
            "jwt": obj.get("jwt"),
            "token": obj.get("token")
        })
        return _obj


