# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.31
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class MfaFormats(str, Enum):
    """
    MfaFormats
    """

    """
    allowed enum values
    """
    NUMERIC = 'numeric'
    ALPHA = 'alpha'
    ALPHANUMERIC = 'alphaNumeric'

    @classmethod
    def from_json(cls, json_str: str) -> MfaFormats:
        """Create an instance of MfaFormats from a JSON string"""
        return MfaFormats(json.loads(json_str))


