# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.25.31
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr, conlist
from openziti_edge_management.models.dial_bind import DialBind
from openziti_edge_management.models.posture_query import PostureQuery

class PostureQueries(BaseModel):
    """
    PostureQueries
    """
    is_passing: StrictBool = Field(..., alias="isPassing")
    policy_id: StrictStr = Field(..., alias="policyId")
    policy_type: Optional[DialBind] = Field(None, alias="policyType")
    posture_queries: conlist(PostureQuery) = Field(..., alias="postureQueries")
    __properties = ["isPassing", "policyId", "policyType", "postureQueries"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PostureQueries:
        """Create an instance of PostureQueries from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in posture_queries (list)
        _items = []
        if self.posture_queries:
            for _item in self.posture_queries:
                if _item:
                    _items.append(_item.to_dict())
            _dict['postureQueries'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PostureQueries:
        """Create an instance of PostureQueries from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PostureQueries.parse_obj(obj)

        _obj = PostureQueries.parse_obj({
            "is_passing": obj.get("isPassing"),
            "policy_id": obj.get("policyId"),
            "policy_type": obj.get("policyType"),
            "posture_queries": [PostureQuery.from_dict(_item) for _item in obj.get("postureQueries")] if obj.get("postureQueries") is not None else None
        })
        return _obj


