# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.25.31
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Dict, Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr
from openziti_edge_management.models.dict[str,_link] import Dict[str, Link]
from openziti_edge_management.models.link import Link

class RouterEntityRef(BaseModel):
    """
    RouterEntityRef
    """
    links: Optional[Dict[str, Link]] = Field(None, alias="_links", description="A map of named links")
    entity: Optional[StrictStr] = None
    id: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    is_online: StrictBool = Field(..., alias="isOnline")
    __properties = ["_links", "entity", "id", "name", "isOnline"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> RouterEntityRef:
        """Create an instance of RouterEntityRef from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each value in links (dict)
        _field_dict = {}
        if self.links:
            for _key in self.links:
                if self.links[_key]:
                    _field_dict[_key] = self.links[_key].to_dict()
            _dict['_links'] = _field_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> RouterEntityRef:
        """Create an instance of RouterEntityRef from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return RouterEntityRef.parse_obj(obj)

        _obj = RouterEntityRef.parse_obj({
            "links": dict(
                (_k, Link.from_dict(_v))
                for _k, _v in obj.get("_links").items()
            )
            if obj.get("_links") is not None
            else None,
            "entity": obj.get("entity"),
            "id": obj.get("id"),
            "name": obj.get("name"),
            "is_online": obj.get("isOnline")
        })
        return _obj


