# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.25.31
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class Semantic(str, Enum):
    """
    Semantic
    """

    """
    allowed enum values
    """
    ALLOF = 'AllOf'
    ANYOF = 'AnyOf'

    @classmethod
    def from_json(cls, json_str: str) -> Semantic:
        """Create an instance of Semantic from a JSON string"""
        return Semantic(json.loads(json_str))


