# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API

    The version of the OpenAPI document: 0.25.31
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr, conlist
from openziti_edge_management.models.tags import Tags

class ServiceCreate(BaseModel):
    """
    ServiceCreate
    """
    configs: Optional[conlist(StrictStr)] = None
    encryption_required: StrictBool = Field(..., alias="encryptionRequired", description="Describes whether connections must support end-to-end encryption on both sides of the connection.")
    name: StrictStr = Field(...)
    role_attributes: Optional[conlist(StrictStr)] = Field(None, alias="roleAttributes")
    tags: Optional[Tags] = None
    terminator_strategy: Optional[StrictStr] = Field(None, alias="terminatorStrategy")
    __properties = ["configs", "encryptionRequired", "name", "roleAttributes", "tags", "terminatorStrategy"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ServiceCreate:
        """Create an instance of ServiceCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of tags
        if self.tags:
            _dict['tags'] = self.tags.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ServiceCreate:
        """Create an instance of ServiceCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ServiceCreate.parse_obj(obj)

        _obj = ServiceCreate.parse_obj({
            "configs": obj.get("configs"),
            "encryption_required": obj.get("encryptionRequired"),
            "name": obj.get("name"),
            "role_attributes": obj.get("roleAttributes"),
            "tags": Tags.from_dict(obj.get("tags")) if obj.get("tags") is not None else None,
            "terminator_strategy": obj.get("terminatorStrategy")
        })
        return _obj


