# coding: utf-8

"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.31
    Contact: help@openziti.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Dict, Optional
from pydantic import BaseModel, Field, StrictStr, conint
from openziti_edge_management.models.entity_ref import EntityRef
from openziti_edge_management.models.link import Link
from openziti_edge_management.models.tags import Tags
from openziti_edge_management.models.terminator_precedence import TerminatorPrecedence

class TerminatorDetail(BaseModel):
    """
    TerminatorDetail
    """
    links: Dict[str, Link] = Field(..., alias="_links", description="A map of named links")
    created_at: datetime = Field(..., alias="createdAt")
    id: StrictStr = Field(...)
    tags: Optional[Tags] = None
    updated_at: datetime = Field(..., alias="updatedAt")
    address: StrictStr = Field(...)
    binding: StrictStr = Field(...)
    cost: conint(strict=True, le=65535, ge=0) = Field(...)
    dynamic_cost: conint(strict=True, le=65535, ge=0) = Field(..., alias="dynamicCost")
    identity: StrictStr = Field(...)
    precedence: TerminatorPrecedence = Field(...)
    router: EntityRef = Field(...)
    router_id: StrictStr = Field(..., alias="routerId")
    service: EntityRef = Field(...)
    service_id: StrictStr = Field(..., alias="serviceId")
    __properties = ["_links", "createdAt", "id", "tags", "updatedAt", "address", "binding", "cost", "dynamicCost", "identity", "precedence", "router", "routerId", "service", "serviceId"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TerminatorDetail:
        """Create an instance of TerminatorDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each value in links (dict)
        _field_dict = {}
        if self.links:
            for _key in self.links:
                if self.links[_key]:
                    _field_dict[_key] = self.links[_key].to_dict()
            _dict['_links'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of tags
        if self.tags:
            _dict['tags'] = self.tags.to_dict()
        # override the default output from pydantic by calling `to_dict()` of router
        if self.router:
            _dict['router'] = self.router.to_dict()
        # override the default output from pydantic by calling `to_dict()` of service
        if self.service:
            _dict['service'] = self.service.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TerminatorDetail:
        """Create an instance of TerminatorDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TerminatorDetail.parse_obj(obj)

        _obj = TerminatorDetail.parse_obj({
            "links": dict(
                (_k, Link.from_dict(_v))
                for _k, _v in obj.get("_links").items()
            )
            if obj.get("_links") is not None
            else None,
            "created_at": obj.get("createdAt"),
            "id": obj.get("id"),
            "tags": Tags.from_dict(obj.get("tags")) if obj.get("tags") is not None else None,
            "updated_at": obj.get("updatedAt"),
            "address": obj.get("address"),
            "binding": obj.get("binding"),
            "cost": obj.get("cost"),
            "dynamic_cost": obj.get("dynamicCost"),
            "identity": obj.get("identity"),
            "precedence": obj.get("precedence"),
            "router": EntityRef.from_dict(obj.get("router")) if obj.get("router") is not None else None,
            "router_id": obj.get("routerId"),
            "service": EntityRef.from_dict(obj.get("service")) if obj.get("service") is not None else None,
            "service_id": obj.get("serviceId")
        })
        return _obj

